[package]
name = "testing"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "testing_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mysql = "26.0.0"
sea-orm = { version = "1.1.0", features = ["sqlx-mysql", "runtime-tokio-native-tls", "macros"] }
chrono = "0.4.40"
rand = "0.9.0"
argon2 = "0.5.3"
infer = "0.19.0"
uuid = "1.15.1"
chrono-tz = "0.10.1"
tokio = { version = "1.36", features = ["full"] }

