//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub mod prelude;

pub mod assigned_chef;
pub mod assigned_ride_staff;
pub mod assigned_waiter;
pub mod broadcast;
pub mod chat;
pub mod chat_oa;
pub mod customer;
pub mod customer_inquiries;
pub mod group_chat;
pub mod itemlog;
pub mod maintenance_report;
pub mod maintenance_request;
pub mod maintenance_task;
pub mod menu;
pub mod menu_history;
pub mod new_restaurant_proposal;
pub mod new_ride_proposal;
pub mod official_account;
pub mod restaurant;
pub mod restaurant_transaction_detail;
pub mod restaurant_transaction_header;
pub mod ride;
pub mod ride_queue;
pub mod ride_removal_proposal;
pub mod souvenir;
pub mod staff;
pub mod store;
