//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "chat")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub chat_id: i32,
    pub sender_staff_id: String,
    pub group_id: String,
    pub message: String,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group_chat::Entity",
        from = "Column::GroupId",
        to = "super::group_chat::Column::GroupId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GroupChat,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::SenderStaffId",
        to = "super::staff::Column::StaffId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::group_chat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupChat.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
