//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "customer")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub customer_id: String,
    pub customer_name: String,
    pub customer_balance: i32,
    pub customer_phone_number: String,
    pub customer_email: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::customer_inquiries::Entity")]
    CustomerInquiries,
    #[sea_orm(has_many = "super::inquries_response::Entity")]
    InquriesResponse,
    #[sea_orm(has_many = "super::itemlog::Entity")]
    Itemlog,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::restaurant_transaction_header::Entity")]
    RestaurantTransactionHeader,
    #[sea_orm(has_many = "super::ride_queue::Entity")]
    RideQueue,
    #[sea_orm(has_many = "super::store_transaction_header::Entity")]
    StoreTransactionHeader,
}

impl Related<super::customer_inquiries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomerInquiries.def()
    }
}

impl Related<super::inquries_response::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InquriesResponse.def()
    }
}

impl Related<super::itemlog::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Itemlog.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::restaurant_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantTransactionHeader.def()
    }
}

impl Related<super::ride_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideQueue.def()
    }
}

impl Related<super::store_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoreTransactionHeader.def()
    }
}

impl Related<super::ride::Entity> for Entity {
    fn to() -> RelationDef {
        super::ride_queue::Relation::Ride.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::ride_queue::Relation::Customer.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
