//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "maintenance_report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub task_id: String,
    pub reporting_staff: String,
    pub report_description: String,
    pub report_image: String,
    pub report_status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maintenance_task::Entity",
        from = "Column::TaskId",
        to = "super::maintenance_task::Column::TaskId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MaintenanceTask,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::ReportingStaff",
        to = "super::staff::Column::StaffId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::maintenance_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MaintenanceTask.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
