//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "menu")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub menu_id: String,
    pub menu_name: String,
    pub menu_description: String,
    pub menu_price: i32,
    pub menu_image: String,
    pub restaurant_id: String,
    pub menu_history_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::menu_history::Entity",
        from = "Column::MenuHistoryId",
        to = "super::menu_history::Column::MenuHistoryId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MenuHistory,
    #[sea_orm(
        belongs_to = "super::restaurant::Entity",
        from = "Column::RestaurantId",
        to = "super::restaurant::Column::RestaurantId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Restaurant,
}

impl Related<super::menu_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MenuHistory.def()
    }
}

impl Related<super::restaurant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Restaurant.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
