//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "menu_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub menu_history_id: String,
    pub menu_history_name: String,
    pub menu_history_price: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::menu::Entity")]
    Menu,
    #[sea_orm(has_many = "super::restaurant_transaction_detail::Entity")]
    RestaurantTransactionDetail,
}

impl Related<super::menu::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Menu.def()
    }
}

impl Related<super::restaurant_transaction_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantTransactionDetail.def()
    }
}

impl Related<super::restaurant_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        super::restaurant_transaction_detail::Relation::RestaurantTransactionHeader.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::restaurant_transaction_detail::Relation::MenuHistory
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
