//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "new_ride_proposal")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub proposal_id: String,
    pub ride_name: String,
    pub ride_description: String,
    pub ride_price: i32,
    pub ride_open_time: Time,
    pub ride_close_time: Time,
    pub file_link: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
