//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "new_store_proposal")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub proposal_id: i32,
    pub store_name: String,
    pub store_description: String,
    pub store_open_time: Time,
    pub store_close_time: Time,
    pub store_location: String,
    pub file_link: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
