//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "official_account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub oa_id: String,
    pub oa_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_oa::Entity")]
    ChatOa,
}

impl Related<super::chat_oa::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatOa.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
