//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "restaurant_transaction_header")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub transaction_id: String,
    pub transaction_date: DateTimeUtc,
    pub customer_id: String,
    pub restaurant_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customer::Entity",
        from = "Column::CustomerId",
        to = "super::customer::Column::CustomerId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Customer,
    #[sea_orm(
        belongs_to = "super::restaurant::Entity",
        from = "Column::RestaurantId",
        to = "super::restaurant::Column::RestaurantId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Restaurant,
    #[sea_orm(has_many = "super::restaurant_order::Entity")]
    RestaurantOrder,
    #[sea_orm(has_many = "super::restaurant_transaction_detail::Entity")]
    RestaurantTransactionDetail,
}

impl Related<super::customer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customer.def()
    }
}

impl Related<super::restaurant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Restaurant.def()
    }
}

impl Related<super::restaurant_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantOrder.def()
    }
}

impl Related<super::restaurant_transaction_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantTransactionDetail.def()
    }
}

impl Related<super::menu_history::Entity> for Entity {
    fn to() -> RelationDef {
        super::restaurant_transaction_detail::Relation::MenuHistory.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::restaurant_transaction_detail::Relation::RestaurantTransactionHeader
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
