//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "restaurant")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub restaurant_id: String,
    pub restaurant_name: String,
    pub restaurant_cuisine: String,
    pub restaurant_description: String,
    pub restaurant_image: String,
    pub restaurant_location: String,
    pub restaurant_open_time: Time,
    pub restaurant_close_time: Time,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assigned_chef::Entity")]
    AssignedChef,
    #[sea_orm(has_many = "super::assigned_waiter::Entity")]
    AssignedWaiter,
    #[sea_orm(has_many = "super::menu::Entity")]
    Menu,
    #[sea_orm(has_many = "super::restaurant_transaction_header::Entity")]
    RestaurantTransactionHeader,
}

impl Related<super::assigned_chef::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssignedChef.def()
    }
}

impl Related<super::assigned_waiter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssignedWaiter.def()
    }
}

impl Related<super::menu::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Menu.def()
    }
}

impl Related<super::restaurant_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantTransactionHeader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
