//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "restaurant_transaction_detail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub transaction_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub menu_history_id: String,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::menu_history::Entity",
        from = "Column::MenuHistoryId",
        to = "super::menu_history::Column::MenuHistoryId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MenuHistory,
    #[sea_orm(
        belongs_to = "super::restaurant_transaction_header::Entity",
        from = "Column::TransactionId",
        to = "super::restaurant_transaction_header::Column::TransactionId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RestaurantTransactionHeader,
}

impl Related<super::menu_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MenuHistory.def()
    }
}

impl Related<super::restaurant_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantTransactionHeader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
