//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "restaurant_order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub order_id: i32,
    pub transaction_id: String,
    pub staff_id: Option<String>,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::restaurant_transaction_header::Entity",
        from = "Column::TransactionId",
        to = "super::restaurant_transaction_header::Column::TransactionId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RestaurantTransactionHeader,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::StaffId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::restaurant_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantTransactionHeader.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
