//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ride")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ride_id: String,
    pub ride_name: String,
    pub ride_description: String,
    pub ride_price: String,
    pub ride_image: String,
    pub ride_open_time: Time,
    pub ride_close_time: Time,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assigned_ride_staff::Entity")]
    AssignedRideStaff,
    #[sea_orm(has_many = "super::maintenance_task::Entity")]
    MaintenanceTask,
    #[sea_orm(has_many = "super::ride_queue::Entity")]
    RideQueue,
    #[sea_orm(has_many = "super::ride_removal_proposal::Entity")]
    RideRemovalProposal,
}

impl Related<super::assigned_ride_staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssignedRideStaff.def()
    }
}

impl Related<super::maintenance_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MaintenanceTask.def()
    }
}

impl Related<super::ride_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideQueue.def()
    }
}

impl Related<super::ride_removal_proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideRemovalProposal.def()
    }
}

impl Related<super::customer::Entity> for Entity {
    fn to() -> RelationDef {
        super::ride_queue::Relation::Customer.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::ride_queue::Relation::Ride.def().rev())
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        super::assigned_ride_staff::Relation::Staff.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::assigned_ride_staff::Relation::Ride.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
