//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "souvenir")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub souvenir_id: String,
    pub souvenir_name: String,
    pub souvenir_image: String,
    pub souvenir_description: String,
    pub souvenir_price: i32,
    pub souvenir_stock: i32,
    pub store_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::store::Entity",
        from = "Column::StoreId",
        to = "super::store::Column::StoreId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Store,
    #[sea_orm(has_many = "super::store_transaction_detail::Entity")]
    StoreTransactionDetail,
}

impl Related<super::store::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl Related<super::store_transaction_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoreTransactionDetail.def()
    }
}

impl Related<super::store_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        super::store_transaction_detail::Relation::StoreTransactionHeader.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::store_transaction_detail::Relation::Souvenir
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
