//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "staff")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub staff_id: String,
    pub staff_name: String,
    pub staff_email: String,
    pub staff_password: String,
    pub staff_role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::assigned_chef::Entity")]
    AssignedChef,
    #[sea_orm(has_many = "super::assigned_ride_staff::Entity")]
    AssignedRideStaff,
    #[sea_orm(has_one = "super::assigned_waiter::Entity")]
    AssignedWaiter,
    #[sea_orm(has_many = "super::chat::Entity")]
    Chat,
    #[sea_orm(has_many = "super::chat_oa::Entity")]
    ChatOa,
    #[sea_orm(has_many = "super::maintenance_report::Entity")]
    MaintenanceReport,
    #[sea_orm(has_many = "super::maintenance_task::Entity")]
    MaintenanceTask,
    #[sea_orm(has_many = "super::restaurant_order::Entity")]
    RestaurantOrder,
    #[sea_orm(has_many = "super::store::Entity")]
    Store,
}

impl Related<super::assigned_chef::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssignedChef.def()
    }
}

impl Related<super::assigned_ride_staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssignedRideStaff.def()
    }
}

impl Related<super::assigned_waiter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssignedWaiter.def()
    }
}

impl Related<super::chat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chat.def()
    }
}

impl Related<super::chat_oa::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatOa.def()
    }
}

impl Related<super::maintenance_report::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MaintenanceReport.def()
    }
}

impl Related<super::maintenance_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MaintenanceTask.def()
    }
}

impl Related<super::restaurant_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantOrder.def()
    }
}

impl Related<super::store::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl Related<super::ride::Entity> for Entity {
    fn to() -> RelationDef {
        super::assigned_ride_staff::Relation::Ride.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::assigned_ride_staff::Relation::Staff.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
