//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "store")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub store_id: String,
    pub store_name: String,
    pub store_description: String,
    pub store_image: String,
    pub store_location: String,
    pub store_open_time: Time,
    pub store_close_time: Time,
    pub staff_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::souvenir::Entity")]
    Souvenir,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::StaffId",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Staff,
    #[sea_orm(has_many = "super::store_removal_proposal::Entity")]
    StoreRemovalProposal,
    #[sea_orm(has_many = "super::store_transaction_header::Entity")]
    StoreTransactionHeader,
}

impl Related<super::souvenir::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Souvenir.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl Related<super::store_removal_proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoreRemovalProposal.def()
    }
}

impl Related<super::store_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoreTransactionHeader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
