//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "store_transaction_detail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub transaction_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub souvenir_id: String,
    pub price: i32,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::souvenir::Entity",
        from = "Column::SouvenirId",
        to = "super::souvenir::Column::SouvenirId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Souvenir,
    #[sea_orm(
        belongs_to = "super::store_transaction_header::Entity",
        from = "Column::TransactionId",
        to = "super::store_transaction_header::Column::TransactionId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StoreTransactionHeader,
}

impl Related<super::souvenir::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Souvenir.def()
    }
}

impl Related<super::store_transaction_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoreTransactionHeader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
