//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "store_transaction_header")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub transaction_id: i32,
    pub transaction_date: DateTimeUtc,
    pub customer_id: String,
    pub store_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customer::Entity",
        from = "Column::CustomerId",
        to = "super::customer::Column::CustomerId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Customer,
    #[sea_orm(
        belongs_to = "super::store::Entity",
        from = "Column::StoreId",
        to = "super::store::Column::StoreId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Store,
    #[sea_orm(has_many = "super::store_transaction_detail::Entity")]
    StoreTransactionDetail,
}

impl Related<super::customer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customer.def()
    }
}

impl Related<super::store::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl Related<super::store_transaction_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoreTransactionDetail.def()
    }
}

impl Related<super::souvenir::Entity> for Entity {
    fn to() -> RelationDef {
        super::store_transaction_detail::Relation::Souvenir.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::store_transaction_detail::Relation::StoreTransactionHeader
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
